import type { LandingContent } from '@/types/landing';

export const landingContent = {
  apiBase: '/api',
  whatsappNumber: '56941946724',
  brand: {
    name: 'INDATTA',
    lockup: '/assets/logos/indatta-lockup-h.svg',
    lockupInverse: '/assets/logos/indatta-lockup-h-inv.svg',
    glyph: '/assets/logos/indatta-isotipo.svg',
    glyphMono: '/assets/logos/indatta-isotipo-mono.svg',
    tagline: 'Data · AI · Intelligent Solutions',
    email: 'admin@indatta.cl',
    location: 'Santiago · Chile',
  },
  nav: [
    { label: 'Soluciones', href: '#soluciones' },
    { label: 'Qué construimos', href: '#showcase' },
    { label: 'Cómo trabajamos', href: '#metodo' },
    { label: 'Por qué INDATTA', href: '#diferencial' },
    { label: 'Conversemos', href: '#contacto' },
  ],
  footerNav: [
    { label: 'Soluciones', href: '#soluciones' },
    { label: 'Qué construimos', href: '#showcase' },
    { label: 'Cómo trabajamos', href: '#metodo' },
    { label: 'Contacto', href: '#contacto' },
  ],
  hero: {
    headingLines: ['Soluciones Data & AI', 'diseñadas alrededor de'],
    headingEmphasis: 'tu negocio',
    lede: 'Conectamos datos, inteligencia artificial, automatización y software para construir soluciones integrales que transforman información en decisiones y acciones.',
    kicker: ['Data', 'Intelligence', 'Action'],
    actions: [
      { label: 'Conversemos sobre tu desafío', href: '#contacto', variant: 'primary', icon: '↗' },
      { label: 'Conoce nuestras soluciones', href: '#soluciones', variant: 'quiet', icon: '↓' },
    ],
    capabilities: ['Data Platforms', 'Artificial Intelligence', 'Analytics', 'Automation', 'Intelligent Software'],
  },
  challenge: {
    heading: {
      index: '02 — El desafío',
      title: 'Los datos existen.',
      emphasis: 'El desafío es convertirlos en resultados.',
      body: 'Las organizaciones generan cada vez más información y utilizan múltiples sistemas, aplicaciones y plataformas. El problema aparece cuando esas piezas están desconectadas, los procesos siguen siendo manuales o las decisiones llegan demasiado tarde.',
    },
    cards: [
      { index: '01', title: 'Información desconectada', body: 'Datos distribuidos entre sistemas, plataformas y equipos.', iconClass: 'broken' },
      { index: '02', title: 'Procesos manuales', body: 'Tareas repetitivas que consumen tiempo y aumentan el riesgo de error.', iconClass: 'repeat', symbol: '↻' },
      { index: '03', title: 'Decisiones tardías', body: 'Información disponible cuando la oportunidad de actuar ya pasó.', iconClass: 'delay' },
      { index: '04', title: 'Conocimiento disperso', body: 'Información crítica distribuida entre documentos, aplicaciones y personas.', iconClass: 'scatter' },
      { index: '05', title: 'Baja visibilidad', body: 'Falta una visión clara y confiable de lo que está ocurriendo.', iconClass: 'radar' },
      { index: '06', title: 'Tecnología sin integración', body: 'Buenas herramientas que funcionan de manera aislada.', iconClass: 'islands' },
    ],
    closeStrong: 'INDATTA conecta esas piezas',
    closeText: 'y construye una solución alrededor del problema.',
  },
  solutions: {
    heading: {
      index: '03 — Soluciones integrales',
      title: 'Soluciones construidas',
      emphasis: 'de punta a punta',
      body: 'No partimos desde una herramienta específica. Diseñamos la combinación de datos, inteligencia, software y automatización necesaria para resolver cada desafío.',
    },
    cards: [
      {
        index: '01',
        title: 'Data Platforms',
        body: 'Construimos plataformas capaces de integrar, procesar, gobernar y disponibilizar la información necesaria para analítica, inteligencia artificial y aplicaciones.',
        tags: ['Data Architecture', 'Data Engineering', 'Integration', 'Lakehouse', 'APIs', 'Streaming', 'Governance', 'Data Quality', 'Observability'],
        className: 'solution-data',
        iconClass: 'solution-icon',
        challenge: 'La información está distribuida entre múltiples sistemas y equipos.',
        result: 'Una única versión confiable del negocio.',
      },
      {
        index: '02',
        title: 'Inteligencia Artificial Aplicada',
        body: 'Diseñamos soluciones de IA conectadas con los datos, conocimiento y procesos reales de la organización.',
        tags: ['Generative AI', 'AI Agents', 'RAG', 'Knowledge AI', 'Machine Learning', 'NLP', 'Computer Vision', 'Prediction'],
        className: 'solution-ai',
        iconClass: 'solution-orb',
        challenge: 'Encontrar y utilizar la información requiere demasiado tiempo.',
        result: 'Acceso inmediato al conocimiento relevante, con un agente conectado a documentos y sistemas internos.',
      },
      {
        index: '03',
        title: 'Analytics & Decision Intelligence',
        body: 'Transformamos datos en inteligencia para entender lo que ocurre, anticipar escenarios y tomar mejores decisiones.',
        tags: ['Analytics', 'KPIs', 'Semantic Models', 'BI', 'Predictive', 'Alerts', 'Decision Support'],
        className: 'solution-analytics',
        iconClass: 'mini-chart',
        challenge: 'Los problemas o desviaciones se detectan demasiado tarde.',
        result: 'Información en tiempo real, alertas y mayor capacidad de anticipación.',
      },
      {
        index: '04',
        title: 'Automation & Intelligent Software',
        body: 'Construimos software, integraciones y automatizaciones capaces de utilizar datos e inteligencia para ejecutar acciones, incluyendo visión computacional cuando el desafío parte de información visual.',
        tags: ['Applications', 'Workflows', 'Process Automation', 'APIs', 'AI Agents', 'Enterprise Integration', 'IoT / Edge', 'Computer Vision'],
        className: 'solution-automation',
        iconClass: 'flow-icon',
        challenge: 'Existe información visual que todavía requiere revisión manual.',
        result: 'Modelos que detectan, clasifican y generan acciones: mayor velocidad, trazabilidad y automatización.',
      },
    ],
    noteStrong: 'No todas las soluciones necesitan todas estas capacidades.',
    noteText: 'Diseñamos cada arquitectura según el problema, contexto, sistemas existentes y objetivos del cliente.',
  },
  dia: {
    heading: {
      index: '04 — Nuestro enfoque',
      title: 'Del dato a',
      emphasis: 'la acción',
      body: 'Una solución puede comenzar en cualquier punto. INDATTA conecta las capacidades necesarias para llevarla desde el dato hasta el resultado.',
    },
    stages: [
      { index: '01', title: 'Conectar y preparar', node: 'DATA', items: ['Sources', 'Integration', 'Data Platforms', 'Cloud', 'APIs', 'Governance', 'Quality'], className: 'stage-data', statLabel: 'Sources', statValue: '18', statDetail: 'connected' },
      { index: '02', title: 'Entender y anticipar', node: 'INTELLIGENCE', items: ['Analytics', 'AI', 'Machine Learning', 'RAG', 'Agents', 'Computer Vision'], className: 'stage-intelligence', statLabel: 'Context', statValue: '92%', statDetail: 'confidence' },
      { index: '03', title: 'Decidir y ejecutar', node: 'ACTION', items: ['Dashboards', 'Applications', 'Automation', 'Workflows', 'Alerts', 'IoT / Edge'], className: 'stage-action', statLabel: 'Status', statValue: 'LIVE', statDetail: 'action ready' },
    ],
  },
  showcase: {
    heading: {
      index: '05 — Showcase interactivo',
      title: 'Explora lo que',
      emphasis: 'podemos construir',
      body: 'Soluciones diseñadas para convertir información en experiencias, decisiones y acciones reales.',
    },
    tabs: [
      { id: 'platform', label: 'Data Platform' },
      { id: 'copilot', label: 'AI Copilot' },
      { id: 'decision', label: 'Decision Intelligence' },
      { id: 'portal', label: 'Project Portal' },
    ],
    demoBadge: 'Datos de demostración',
  },
  method: {
    heading: {
      index: '06 — Cómo trabajamos',
      title: 'Tu desafío probablemente',
      emphasis: 'no cabe dentro de una caja.',
      body: 'No partimos preguntando qué herramienta quieres implementar. Primero entendemos qué necesitas resolver. Después diseñamos la arquitectura y la combinación de datos, IA, analítica y automatización adecuada, sin depender de un proveedor.',
    },
    steps: [
      { index: '01', title: 'Entendemos', body: 'Negocio, procesos, sistemas, datos, restricciones y objetivos.' },
      { index: '02', title: 'Diseñamos', body: 'Definimos solución, arquitectura, experiencia y roadmap.' },
      { index: '03', title: 'Construimos', body: 'Desarrollamos datos, IA, integraciones, aplicaciones y automatizaciones.' },
      { index: '04', title: 'Validamos', body: 'Probamos con usuarios, información y escenarios reales.' },
      { index: '05', title: 'Desplegamos', body: 'Llevamos progresivamente la solución hacia producción.' },
      { index: '06', title: 'Evolucionamos', body: 'Medimos resultados y continuamos mejorando la solución.' },
    ],
    stackLabel: 'Trabajamos con',
    stackText: 'Data & Cloud · Artificial Intelligence · Analytics & Intelligence · Automation & Software, seleccionadas según el contexto, nunca según un proveedor.',
    manifestoStart: 'Una solución.',
    manifestoEmphasis: 'Un equipo.',
    manifestoEnd: 'De la idea a producción.',
  },
  difference: {
    heading: {
      index: '07 — Por qué INDATTA',
      title: 'Tecnología diseñada',
      emphasis: 'alrededor del problema',
    },
    principles: [
      { index: '01', title: 'End-to-end', body: 'Desde la integración del dato hasta la solución que lo utiliza.' },
      { index: '02', title: 'Arquitectura antes que improvisación', body: 'Diseñamos pensando en escalabilidad y evolución.' },
      { index: '03', title: 'Tecnología agnóstica', body: 'Seleccionamos herramientas según el problema, no según un proveedor.' },
      { index: '04', title: 'IA conectada al negocio', body: 'Genera valor cuando tiene datos, contexto y procesos reales.' },
      { index: '05', title: 'Integración con tu ecosistema', body: 'Construimos sobre plataformas y sistemas existentes cuando tiene sentido.' },
      { index: '06', title: 'Visibilidad permanente', body: 'Sabes qué estamos construyendo y cómo avanza.' },
    ],
    portalItems: [
      { title: 'Arquitectura', body: 'Documento vigente, con sus decisiones' },
      { title: 'Entregables', body: 'Qué se completó y qué sigue' },
      { title: 'Decisiones', body: 'Qué se acordó, cuándo y por qué' },
      { title: 'Riesgos', body: 'Qué podría bloquear el avance' },
      { title: 'Responsables', body: 'Quién hace qué, en cada etapa' },
    ],
    visibility: {
      index: 'Project visibility',
      title: 'Tú también ves cómo avanza tu proyecto.',
      body: 'Documentación, arquitectura, entregables, decisiones, riesgos, responsables y próximos pasos en un mismo lugar.',
    },
  },
  contact: {
    industryHeading: '08 — Tecnología que se adapta al contexto',
    industryBody: 'Nuestra especialización no está limitada por una industria. Está en conectar datos, inteligencia y tecnología para resolver problemas complejos.',
    industries: ['Retail', 'Servicios', 'Finanzas', 'Energía', 'Manufactura', 'Logística', 'Minería'],
    heading: {
      index: 'Conversemos',
      title: 'Cuéntanos el problema.',
      emphasis: 'Diseñemos la solución.',
      body: 'No necesitas llegar con una arquitectura definida ni saber qué tecnología utilizar. Cuéntanos qué necesitas resolver y conversemos sobre cómo abordarlo.',
    },
    path: ['Problema', 'Evaluación', 'Alcance', 'Proyecto'],
    directLabel: 'Contacto directo',
    solutionOptions: ['Computer Vision', 'Sistemas agénticos', 'Monitoreo con decisiones en línea', 'Plataforma de monitoreo y control de activos', 'Integraciones IoT y periféricos', 'Sistemas RAG', 'Desarrollo a medida con sistemas de agentes', 'No estoy seguro todavía'],
    channels: ['Correo', 'Teléfono', 'WhatsApp'],
    submitByChannel: { Correo: 'Conversemos', Teléfono: 'Solicitar llamada', WhatsApp: 'Continuar en WhatsApp' },
    okByChannel: { Correo: 'Recibimos tu solicitud. Te contactaremos por correo.', Teléfono: 'Recibimos tu solicitud. Te contactaremos por teléfono.' },
    consent: 'Acepto que INDATTA use estos datos para contactarme y evaluar mi proyecto.',
    globalNote: 'Tu solicitud llega directo a nuestro equipo. Si eliges WhatsApp, te llevamos a la conversación después de confirmar la recepción.',
  },
} satisfies LandingContent;
